ner_model_path: "outputs/models/ner_model/20220825/"
taxonomy_name: "toy"
taxonomy_path: ""
clean_job_ads: True
min_multiskill_length: 75
taxonomy_embedding_file_name: ""
prev_skill_matches_file_name: ""
hard_labelled_skills_file_name: ""
hier_name_mapper_file_name: ""
num_hier_levels: 2
skill_type_dict:
  { "skill_types": ["skill"], "hier_types": ["skill_group_2", "skill_group_3"] }
match_thresholds_dict:
  {
    "skill_match_thresh": 0.7,
    "top_tax_skills": { 1: 0.5, 2: 0.5, 3: 0.5 },
    "max_share": { 1: 0, 2: 0.2, 3: 0.2 },
  }
hier_name_mapper:
  {
    "S1": "communication, collaboration and creativity",
    "S1.0": "communication, collaboration and creativity",
    "S1.0.0": "communication, collaboration and creativity",
    "S1.2.1": "mathematics",
    "S1.4": "presenting information",
    "S1.4.3": "presenting information in legal proceedings",
    "S5": "working with computers",
    "S5.6": "using digital tools for collaboration, content creation and problem solving",
    "S5.6.1": "using digital tools for collaboration and productivity",
    "S5.5": "accessing and analysing digital data",
    "S5.5.2": "managing and analysing digital data",
  }

skill_name_col: "description"
skill_id_col: "id"
skill_hier_info_col: "hierarchy_levels"
skill_type_col: "type"
